// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtb7G0yN_kZ0zi1y9SGsYT1mt1CSyxwDI',
    appId: '1:413887432891:web:8eff0b11a4aab29699419e',
    messagingSenderId: '413887432891',
    projectId: 'smart-parking-8353f',
    authDomain: 'smart-parking-8353f.firebaseapp.com',
    storageBucket: 'smart-parking-8353f.appspot.com',
    measurementId: 'G-FQHJMFFHKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvFJFD_zoy05rzX11PdF3gHz7aXS3jV_o',
    appId: '1:413887432891:android:0adb9b62c2f31ece99419e',
    messagingSenderId: '413887432891',
    projectId: 'smart-parking-8353f',
    storageBucket: 'smart-parking-8353f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDprPJ7L8glC89jSWl0pcWkv5D7tm_q1_8',
    appId: '1:413887432891:ios:76fe1b84453ad8af99419e',
    messagingSenderId: '413887432891',
    projectId: 'smart-parking-8353f',
    storageBucket: 'smart-parking-8353f.appspot.com',
    iosClientId: '413887432891-antssijhaa5602otuom1r2m6pivoec3h.apps.googleusercontent.com',
    iosBundleId: 'com.progress.app.smartParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDprPJ7L8glC89jSWl0pcWkv5D7tm_q1_8',
    appId: '1:413887432891:ios:76fe1b84453ad8af99419e',
    messagingSenderId: '413887432891',
    projectId: 'smart-parking-8353f',
    storageBucket: 'smart-parking-8353f.appspot.com',
    iosClientId: '413887432891-antssijhaa5602otuom1r2m6pivoec3h.apps.googleusercontent.com',
    iosBundleId: 'com.progress.app.smartParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtb7G0yN_kZ0zi1y9SGsYT1mt1CSyxwDI',
    appId: '1:413887432891:web:a94b4d3a25e4f36c99419e',
    messagingSenderId: '413887432891',
    projectId: 'smart-parking-8353f',
    authDomain: 'smart-parking-8353f.firebaseapp.com',
    storageBucket: 'smart-parking-8353f.appspot.com',
    measurementId: 'G-WPD80PQZEC',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBtb7G0yN_kZ0zi1y9SGsYT1mt1CSyxwDI',
    appId: '1:413887432891:web:5f80e7fa68d0b59699419e',
    messagingSenderId: '413887432891',
    projectId: 'smart-parking-8353f',
    authDomain: 'smart-parking-8353f.firebaseapp.com',
    storageBucket: 'smart-parking-8353f.appspot.com',
    measurementId: 'G-ETCB49SE4W',
  );
}
